### ISSUE TITLE
file fonctions-fr.php

### ISSUE THREAD

**Issue by alexnikvik** [ycollatin/Crustula#1]
When the answer is wrong appears notification: 
Notice: Undefined variable: message in /var/www/html/crustula/fonctions-fr.php on line 238
I tested corrected file.

**Comment by ycollatin** [comment]
I can't reproduce it (PHP version 7.4.15). The variable at 238 is $niveau, which is assigned at l. 101 :
`
if (isset($_POST['niveau']))

            $niveau = $_POST['niveau'];

if (!isset($niveau)) {                   // initialisation

            $status = str_repeat('0', count($data));

            $niveau = 1;

        }`

**Comment by alexnikvik** [comment]
OK Probably I should upgrade PHP.

**Comment by alexnikvik** [comment]
No more error reports from this file.
