### ISSUE TITLE
sov5.php

### ISSUE THREAD

**Issue by alexnikvik** [ycollatin/Crustula#3]
Fatal error: Uncaught Error: Call to undefined function ereg_replace() in /var/www/html/crustula/sov5.php:100 Stack trace: #0 /var/www/html/crustula/sov5.php(229): conj(Array, '3', 's', 'i') #1 /var/www/html/crustula/sov5.php(356): sLat(Array) #2 {main} thrown in /var/www/html/crustula/sov5.php on line 100

**Comment by ycollatin** [comment]
fixed. ereg_replace -> preg_replace, and delimiters /.../.
